# config.yaml

API:
  SDWebUI: "http://localhost:7860"

PROMPT:
  fixed:
    POS_T: "best quality, "
    NEG_T: "FastNegativeV2, (easynegative:2), ng_deepnegative_v1_75t, low quality, blurry, greyscale, comic art, text, watermark, signature, ugly, bad anatomy, cropped, censored, xray"
  style:
    chibi: "[System: Chibi Style] Cute, exaggerated features, big eyes."
    realistic: "[System: Realistic Style] Detailed, lifelike proportions."

BASEMODEL:
  style:
    Chibi: "cuteyukimixAdorable_kemiaomiao.safetensors"
    Anime 1: "cuteyukimixAdorable_kemiaomiao.safetensors"
    Anime 2: "AOM3A1B_orangemixs.safetensors"
    Semi-Realistic: "AOM3A1B_orangemixs.safetensors"
    Realistic: "majicmixRealistic_v7.safetensors"
